/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IThirdParty, IThirdPartyInterface } from "../IThirdParty";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "winner",
        type: "address",
      },
    ],
    name: "notifyPlayerWon",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IThirdParty__factory {
  static readonly abi = _abi;
  static createInterface(): IThirdPartyInterface {
    return new Interface(_abi) as IThirdPartyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IThirdParty {
    return new Contract(address, _abi, runner) as unknown as IThirdParty;
  }
}
