/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IVipToken, IVipTokenInterface } from "../IVipToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVipToken__factory {
  static readonly abi = _abi;
  static createInterface(): IVipTokenInterface {
    return new Interface(_abi) as IVipTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVipToken {
    return new Contract(address, _abi, runner) as unknown as IVipToken;
  }
}
