/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IZyBeacon, IZyBeaconInterface } from "../IZyBeacon";

const _abi = [
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZyBeacon__factory {
  static readonly abi = _abi;
  static createInterface(): IZyBeaconInterface {
    return new Interface(_abi) as IZyBeaconInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IZyBeacon {
    return new Contract(address, _abi, runner) as unknown as IZyBeacon;
  }
}
