/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZyERC1822Proxiable,
  IZyERC1822ProxiableInterface,
} from "../IZyERC1822Proxiable";

const _abi = [
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZyERC1822Proxiable__factory {
  static readonly abi = _abi;
  static createInterface(): IZyERC1822ProxiableInterface {
    return new Interface(_abi) as IZyERC1822ProxiableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZyERC1822Proxiable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IZyERC1822Proxiable;
  }
}
