/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { MinAddress, MinAddressInterface } from "../MinAddress";

const _abi = [
  {
    inputs: [],
    name: "AddressError",
    type: "error",
  },
  {
    inputs: [],
    name: "AddressInsuffcientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "AddressNotContract",
    type: "error",
  },
] as const;

export class MinAddress__factory {
  static readonly abi = _abi;
  static createInterface(): MinAddressInterface {
    return new Interface(_abi) as MinAddressInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MinAddress {
    return new Contract(address, _abi, runner) as unknown as MinAddress;
  }
}
