/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { MinStrings, MinStringsInterface } from "../MinStrings";

const _abi = [
  {
    inputs: [],
    name: "InvalidStringBytes",
    type: "error",
  },
] as const;

export class MinStrings__factory {
  static readonly abi = _abi;
  static createInterface(): MinStringsInterface {
    return new Interface(_abi) as MinStringsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MinStrings {
    return new Contract(address, _abi, runner) as unknown as MinStrings;
  }
}
