/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { VipToken, VipTokenInterface } from "../VipToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class VipToken__factory {
  static readonly abi = _abi;
  static createInterface(): VipTokenInterface {
    return new Interface(_abi) as VipTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): VipToken {
    return new Contract(address, _abi, runner) as unknown as VipToken;
  }
}
