/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ISemver, ISemverInterface } from "../ISemver";

const _abi = [
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISemver__factory {
  static readonly abi = _abi;
  static createInterface(): ISemverInterface {
    return new utils.Interface(_abi) as ISemverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISemver {
    return new Contract(address, _abi, signerOrProvider) as ISemver;
  }
}
