/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IVipToken, IVipTokenInterface } from "../IVipToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVipToken__factory {
  static readonly abi = _abi;
  static createInterface(): IVipTokenInterface {
    return new utils.Interface(_abi) as IVipTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVipToken {
    return new Contract(address, _abi, signerOrProvider) as IVipToken;
  }
}
