/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IZyERC1822Proxiable,
  IZyERC1822ProxiableInterface,
} from "../IZyERC1822Proxiable";

const _abi = [
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IZyERC1822Proxiable__factory {
  static readonly abi = _abi;
  static createInterface(): IZyERC1822ProxiableInterface {
    return new utils.Interface(_abi) as IZyERC1822ProxiableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZyERC1822Proxiable {
    return new Contract(address, _abi, signerOrProvider) as IZyERC1822Proxiable;
  }
}
