/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { VipToken, VipTokenInterface } from "../VipToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class VipToken__factory {
  static readonly abi = _abi;
  static createInterface(): VipTokenInterface {
    return new utils.Interface(_abi) as VipTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VipToken {
    return new Contract(address, _abi, signerOrProvider) as VipToken;
  }
}
