/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IBingoFeeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "afterGameTimeOut"
      | "afterGameWon"
      | "beforeJoin"
      | "getGameFee"
      | "leave"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "afterGameTimeOut",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "afterGameWon",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeJoin",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "leave",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "afterGameTimeOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterGameWon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "beforeJoin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGameFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "leave", data: BytesLike): Result;
}

export interface IBingoFee extends BaseContract {
  connect(runner?: ContractRunner | null): IBingoFee;
  waitForDeployment(): Promise<this>;

  interface: IBingoFeeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  afterGameTimeOut: TypedContractMethod<
    [gameId: BigNumberish, betSize: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  afterGameWon: TypedContractMethod<
    [gameId: BigNumberish, betSize: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  beforeJoin: TypedContractMethod<
    [from: AddressLike, betSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  getGameFee: TypedContractMethod<
    [gameId: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;

  leave: TypedContractMethod<
    [to: AddressLike, betSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "afterGameTimeOut"
  ): TypedContractMethod<
    [gameId: BigNumberish, betSize: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterGameWon"
  ): TypedContractMethod<
    [gameId: BigNumberish, betSize: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeJoin"
  ): TypedContractMethod<
    [from: AddressLike, betSize: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGameFee"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "leave"
  ): TypedContractMethod<
    [to: AddressLike, betSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
