/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IGameLineup {
  export type WaitingInfoStruct = {
    level: BigNumberish;
    minWinCounts: BigNumberish;
    minWinRate: BigNumberish;
    maxWinCounts: BigNumberish;
    maxWinRate: BigNumberish;
    startedAt: BigNumberish;
    endedAt: BigNumberish;
    betSize: BigNumberish;
    expectedLines: BigNumberish;
    minNumber: BigNumberish;
    maxNumber: BigNumberish;
  };

  export type WaitingInfoStructOutput = [
    level: bigint,
    minWinCounts: bigint,
    minWinRate: bigint,
    maxWinCounts: bigint,
    maxWinRate: bigint,
    startedAt: bigint,
    endedAt: bigint,
    betSize: bigint,
    expectedLines: bigint,
    minNumber: bigint,
    maxNumber: bigint
  ] & {
    level: bigint;
    minWinCounts: bigint;
    minWinRate: bigint;
    maxWinCounts: bigint;
    maxWinRate: bigint;
    startedAt: bigint;
    endedAt: bigint;
    betSize: bigint;
    expectedLines: bigint;
    minNumber: bigint;
    maxNumber: bigint;
  };
}

export interface IGameLineupInterface extends Interface {
  getFunction(
    nameOrSignature: "activeLevels" | "join" | "leave" | "lineupUsers" | "start"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LineupJoined" | "LineupLeft"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeLevels",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "join",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "leave", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lineupUsers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "start", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "activeLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "join", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "leave", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lineupUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "start", data: BytesLike): Result;
}

export namespace LineupJoinedEvent {
  export type InputTuple = [player: AddressLike];
  export type OutputTuple = [player: string];
  export interface OutputObject {
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LineupLeftEvent {
  export type InputTuple = [player: AddressLike];
  export type OutputTuple = [player: string];
  export interface OutputObject {
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IGameLineup extends BaseContract {
  connect(runner?: ContractRunner | null): IGameLineup;
  waitForDeployment(): Promise<this>;

  interface: IGameLineupInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeLevels: TypedContractMethod<
    [],
    [
      [bigint, IGameLineup.WaitingInfoStructOutput[]] & {
        wins: bigint;
        list: IGameLineup.WaitingInfoStructOutput[];
      }
    ],
    "view"
  >;

  join: TypedContractMethod<
    [level: BigNumberish, zkCard: BytesLike],
    [void],
    "nonpayable"
  >;

  leave: TypedContractMethod<[], [void], "nonpayable">;

  lineupUsers: TypedContractMethod<[], [[bigint, string[]]], "view">;

  start: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeLevels"
  ): TypedContractMethod<
    [],
    [
      [bigint, IGameLineup.WaitingInfoStructOutput[]] & {
        wins: bigint;
        list: IGameLineup.WaitingInfoStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "join"
  ): TypedContractMethod<
    [level: BigNumberish, zkCard: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "leave"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lineupUsers"
  ): TypedContractMethod<[], [[bigint, string[]]], "view">;
  getFunction(
    nameOrSignature: "start"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "LineupJoined"
  ): TypedContractEvent<
    LineupJoinedEvent.InputTuple,
    LineupJoinedEvent.OutputTuple,
    LineupJoinedEvent.OutputObject
  >;
  getEvent(
    key: "LineupLeft"
  ): TypedContractEvent<
    LineupLeftEvent.InputTuple,
    LineupLeftEvent.OutputTuple,
    LineupLeftEvent.OutputObject
  >;

  filters: {
    "LineupJoined(address)": TypedContractEvent<
      LineupJoinedEvent.InputTuple,
      LineupJoinedEvent.OutputTuple,
      LineupJoinedEvent.OutputObject
    >;
    LineupJoined: TypedContractEvent<
      LineupJoinedEvent.InputTuple,
      LineupJoinedEvent.OutputTuple,
      LineupJoinedEvent.OutputObject
    >;

    "LineupLeft(address)": TypedContractEvent<
      LineupLeftEvent.InputTuple,
      LineupLeftEvent.OutputTuple,
      LineupLeftEvent.OutputObject
    >;
    LineupLeft: TypedContractEvent<
      LineupLeftEvent.InputTuple,
      LineupLeftEvent.OutputTuple,
      LineupLeftEvent.OutputObject
    >;
  };
}
