/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IUserCenter {
  export type PlayerStatisticsStruct = {
    joined: BigNumberish;
    joinAmount: BigNumberish;
    wins: BigNumberish;
    winAmount: BigNumberish;
  };

  export type PlayerStatisticsStructOutput = [
    joined: bigint,
    joinAmount: bigint,
    wins: bigint,
    winAmount: bigint
  ] & { joined: bigint; joinAmount: bigint; wins: bigint; winAmount: bigint };
}

export interface IUserCenterInterface extends Interface {
  getFunction(nameOrSignature: "userRecords"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "userRecords",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "userRecords",
    data: BytesLike
  ): Result;
}

export interface IUserCenter extends BaseContract {
  connect(runner?: ContractRunner | null): IUserCenter;
  waitForDeployment(): Promise<this>;

  interface: IUserCenterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  userRecords: TypedContractMethod<
    [user: AddressLike],
    [
      [
        IUserCenter.PlayerStatisticsStructOutput,
        IUserCenter.PlayerStatisticsStructOutput
      ] & {
        current: IUserCenter.PlayerStatisticsStructOutput;
        overall: IUserCenter.PlayerStatisticsStructOutput;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "userRecords"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [
        IUserCenter.PlayerStatisticsStructOutput,
        IUserCenter.PlayerStatisticsStructOutput
      ] & {
        current: IUserCenter.PlayerStatisticsStructOutput;
        overall: IUserCenter.PlayerStatisticsStructOutput;
      }
    ],
    "view"
  >;

  filters: {};
}
